/*
 * LetsJamApi
 * RESTful Api for LetsJam Website. MWT 2020/2021 - Jacopo Cicoria, Antonio Angelini, Mattia Lenza
 *
 * OpenAPI spec version: 1.0
 * Contact: mattia.lenza@student.univaq.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.univaq.disim.mwt.letsjamrestapi.models;

import javax.annotation.Generated;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * NewMusicSheetSong
 */
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-01-07T15:13:39.019Z[GMT]")
public class NewMusicSheetSong   {
  @JsonProperty("id")
  private BigDecimal id = null;

  @JsonProperty("spotifyId")
  private String spotifyId = null;

  @JsonProperty("songtype")
  private Boolean songtype = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("author")
  private String author = null;

  @JsonProperty("genreId")
  private BigDecimal genreId = null;

  public NewMusicSheetSong id(BigDecimal id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   **/
  @JsonProperty("id")
  @Schema(description = "")
  @Valid
 @DecimalMin("1")  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public NewMusicSheetSong spotifyId(String spotifyId) {
    this.spotifyId = spotifyId;
    return this;
  }

  /**
   * Get spotifyId
   * @return spotifyId
   **/
  @JsonProperty("spotifyId")
  @Schema(description = "")
  public String getSpotifyId() {
    return spotifyId;
  }

  public void setSpotifyId(String spotifyId) {
    this.spotifyId = spotifyId;
  }

  public NewMusicSheetSong songtype(Boolean songtype) {
    this.songtype = songtype;
    return this;
  }

  /**
   * Get songtype
   * @return songtype
   **/
  @JsonProperty("songtype")
  @Schema(required = true, description = "")
  @NotNull
  public Boolean isSongtype() {
    return songtype;
  }

  public void setSongtype(Boolean songtype) {
    this.songtype = songtype;
  }

  public NewMusicSheetSong title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   **/
  @JsonProperty("title")
  @Schema(required = true, description = "")
  @NotNull
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public NewMusicSheetSong author(String author) {
    this.author = author;
    return this;
  }

  /**
   * Get author
   * @return author
   **/
  @JsonProperty("author")
  @Schema(required = true, description = "")
  @NotNull
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public NewMusicSheetSong genreId(BigDecimal genreId) {
    this.genreId = genreId;
    return this;
  }

  /**
   * Get genreId
   * minimum: 1
   * @return genreId
   **/
  @JsonProperty("genreId")
  @Schema(required = true, description = "")
  @NotNull
  @Valid
 @DecimalMin("1")  public BigDecimal getGenreId() {
    return genreId;
  }

  public void setGenreId(BigDecimal genreId) {
    this.genreId = genreId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewMusicSheetSong newMusicSheetSong = (NewMusicSheetSong) o;
    return Objects.equals(this.id, newMusicSheetSong.id) &&
        Objects.equals(this.spotifyId, newMusicSheetSong.spotifyId) &&
        Objects.equals(this.songtype, newMusicSheetSong.songtype) &&
        Objects.equals(this.title, newMusicSheetSong.title) &&
        Objects.equals(this.author, newMusicSheetSong.author) &&
        Objects.equals(this.genreId, newMusicSheetSong.genreId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, spotifyId, songtype, title, author, genreId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewMusicSheetSong {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    spotifyId: ").append(toIndentedString(spotifyId)).append("\n");
    sb.append("    songtype: ").append(toIndentedString(songtype)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    genreId: ").append(toIndentedString(genreId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
